language: rust
rust: nightly
sudo: false

env:
  global:
    - RUST_BACKTRACE=1
    - secure: E33II/ctVUNigc5wuh153OX/7RUje43G3I9i5+PibEiFPCpKIJpHZA9LfKHABqOBVPgBLdWkretWgKn4Whfb9e2NMC8Nzn8Pch68b7yPZ2Ee0zLWr2M2gJ95PwTn3ZyFaMuZOAa+TgEU9buVIXTdgM+FHK+jXwU0qqNL2XCF5YM=

cache: cargo

script:
  - cargo build
  - cargo test --all

before_deploy:
  - cargo run --release --bin coverage -- --json coverage.json

deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
