[package]
name = "meta"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.1"
rand = "0.3"
regex = "0.1"
reqwest = "0.2"
toml = "0.1"
url = "1.1.1"
walkdir = "0.1"

find-unimplemented-tasks = { path = "../tasks/rosetta-code/find-unimplemented-tasks" }
