[package]
name = "pangram-checker"
version = "0.1.0"
authors = ["Ky Waegel <kwaegel@users.noreply.github.com>"]

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Pangram_checker"

[dependencies]
