[package]
name = "remove-lines-from-a-file"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Remove_lines_from_a_file"

[dependencies]
docopt = "0.8"
serde = "1"
serde_derive = "1"
