[package]
name = "parallel-calculations"
version = "0.1.0"

[package.metadata.rosettacode]
url = "http://rosettacode.org/wiki/Parallel_calculations"

[dependencies]
eventual = "0.1.6"
prime-decomposition = { path = "../prime-decomposition" }
